// Copyright (c) 2026 The Dash Core developers
// Distributed under the MIT software license, see the accompanying
// file COPYING or http://www.opensource.org/licenses/mit-license.php.

//! Acceptance test: replay every query in
//! src/test/data/platform/drive_query_vectors.json (generated by the
//! platform-drive-vectors crate from real dashpay/platform v4.0.0 + grovedb
//! v5.0.0 code) through the crate's verify_* functions. Passing proves that
//! the DriveDocumentQuery / contested-vote-poll constructions match the
//! query shapes the server executed, and that the proofs stay verifiable
//! across a platform minor-version bump (crate pins v4.1.0).
//!
//! Query parameters that are not carried in the vector file (DPNS labels,
//! limits) mirror src/test/platform_drive_tests.cpp.

use dash_platform_ffi::verify;
use serde::Deserialize;
use serde_json::Value;

#[derive(Deserialize)]
struct VectorFile {
    platform_repo_tag: String,
    identity_id: String,
    queries: Vec<QueryVector>,
}

#[derive(Deserialize)]
struct QueryVector {
    name: String,
    #[serde(default)]
    query: Value,
    grovedb_proof_hex: String,
    expected_root_hash_hex: String,
    expected: Value,
}

fn hexv(hex: &str) -> Vec<u8> {
    hex::decode(hex).expect("bad hex in test vector")
}

fn load() -> VectorFile {
    let file: VectorFile = serde_json::from_str(include_str!(
        "../../../src/test/data/platform/drive_query_vectors.json"
    ))
    .expect("parse drive_query_vectors.json");
    assert_eq!(file.platform_repo_tag, "v4.0.0");
    file
}

fn query<'a>(file: &'a VectorFile, name: &str) -> &'a QueryVector {
    file.queries
        .iter()
        .find(|query| query.name == name)
        .unwrap_or_else(|| panic!("query vector not found: {name}"))
}

#[test]
fn identity_balance() {
    let file = load();
    let q = query(&file, "identity_balance");
    let result = verify::verify_identity_balance(&hexv(&q.grovedb_proof_hex), &hexv(&file.identity_id))
        .expect("identity balance verify");
    assert_eq!(hex::encode(result.root_hash), q.expected_root_hash_hex);
    assert_eq!(result.value, q.expected["balance"].as_u64());
    assert!(result.value.is_some());
}

#[test]
fn identity_revision() {
    let file = load();
    let q = query(&file, "identity_revision");
    let result =
        verify::verify_identity_revision(&hexv(&q.grovedb_proof_hex), &hexv(&file.identity_id))
            .expect("identity revision verify");
    assert_eq!(hex::encode(result.root_hash), q.expected_root_hash_hex);
    assert_eq!(result.value, q.expected["revision"].as_u64());
}

#[test]
fn identity_nonce() {
    let file = load();
    let q = query(&file, "identity_nonce");
    let result = verify::verify_identity_nonce(&hexv(&q.grovedb_proof_hex), &hexv(&file.identity_id))
        .expect("identity nonce verify");
    assert_eq!(hex::encode(result.root_hash), q.expected_root_hash_hex);
    assert_eq!(result.value, q.expected["nonce"].as_u64());
}

#[test]
fn identity_contract_nonce() {
    let file = load();
    let q = query(&file, "identity_contract_nonce");
    let contract_id = hexv(q.query["contract_id"].as_str().expect("contract_id"));
    let result = verify::verify_identity_contract_nonce(
        &hexv(&q.grovedb_proof_hex),
        &hexv(&file.identity_id),
        &contract_id,
    )
    .expect("identity contract nonce verify");
    assert_eq!(hex::encode(result.root_hash), q.expected_root_hash_hex);
    assert_eq!(result.value, q.expected["nonce"].as_u64());
}

#[test]
fn identity_keys() {
    use dpp::identity::identity_public_key::accessors::v0::IdentityPublicKeyGettersV0;
    use dpp::identity::IdentityPublicKey;
    use dpp::serialization::PlatformDeserializable;

    let file = load();
    let q = query(&file, "identity_keys");
    let result = verify::verify_identity_keys(&hexv(&q.grovedb_proof_hex), &hexv(&file.identity_id))
        .expect("identity keys verify");
    assert_eq!(hex::encode(result.root_hash), q.expected_root_hash_hex);
    let keys = result.keys.expect("identity proven present");

    let expected_keys: Vec<IdentityPublicKey> = q.expected["serialized_keys"]
        .as_array()
        .expect("serialized_keys")
        .iter()
        .map(|serialized| {
            IdentityPublicKey::deserialize_from_bytes(&hexv(serialized.as_str().unwrap()))
                .expect("expected key deserializes")
        })
        .collect();
    assert_eq!(keys.len(), expected_keys.len());
    for (key, expected) in keys.iter().zip(&expected_keys) {
        assert_eq!(key.id, expected.id());
        assert_eq!(key.purpose, expected.purpose() as u8);
        assert_eq!(key.security_level, expected.security_level() as u8);
        assert_eq!(key.key_type, expected.key_type() as u8);
        assert_eq!(key.read_only, expected.read_only());
        assert_eq!(key.data, expected.data().to_vec());
        assert_eq!(key.disabled_at, expected.disabled_at());
    }
    assert_eq!(
        keys.iter().map(|key| key.id).collect::<Vec<_>>(),
        vec![0, 1, 2]
    );
}

#[test]
fn identity_by_public_key_hash() {
    let file = load();
    {
        let q = query(&file, "identity_by_public_key_hash_present");
        let hash = hexv(q.query["public_key_hash"].as_str().expect("public_key_hash"));
        let result = verify::verify_identity_id_by_pubkey_hash(&hexv(&q.grovedb_proof_hex), &hash)
            .expect("identity by pubkey hash verify");
        assert_eq!(hex::encode(result.root_hash), q.expected_root_hash_hex);
        assert_eq!(
            result.id.map(hex::encode),
            q.expected["identity_id"].as_str().map(String::from)
        );
    }
    {
        let q = query(&file, "identity_by_public_key_hash_absent");
        let hash = hexv(q.query["public_key_hash"].as_str().expect("public_key_hash"));
        let result = verify::verify_identity_id_by_pubkey_hash(&hexv(&q.grovedb_proof_hex), &hash)
            .expect("identity by pubkey hash verify (absent)");
        assert_eq!(hex::encode(result.root_hash), q.expected_root_hash_hex);
        assert!(result.id.is_none(), "hash must be proven absent");
    }
}

fn check_documents(q: &QueryVector, result: dash_platform_ffi::types::DocsResult) {
    assert_eq!(
        hex::encode(result.root_hash),
        q.expected_root_hash_hex,
        "{}: root hash",
        q.name
    );
    let expected: Vec<String> = q.expected["documents"]
        .as_array()
        .expect("documents")
        .iter()
        .map(|document| document.as_str().unwrap().to_string())
        .collect();
    assert_eq!(
        result
            .documents
            .iter()
            .map(hex::encode)
            .collect::<Vec<_>>(),
        expected,
        "{}: documents",
        q.name
    );
}

// Parameters mirror src/test/platform_drive_tests.cpp document_index_proofs.
#[test]
fn dpns_exact() {
    let file = load();
    let q = query(&file, "dpns_exact");
    let result = verify::verify_dpns_name_exact(&hexv(&q.grovedb_proof_hex), "alice")
        .expect("dpns exact verify");
    check_documents(q, result);
}

#[test]
fn dpns_prefix() {
    let file = load();
    let q = query(&file, "dpns_prefix");
    let result = verify::verify_dpns_name_prefix(&hexv(&q.grovedb_proof_hex), "ali", 25)
        .expect("dpns prefix verify");
    check_documents(q, result);
}

#[test]
fn dpns_by_identity() {
    let file = load();
    let q = query(&file, "dpns_by_identity");
    let result = verify::verify_dpns_names_by_identity(
        &hexv(&q.grovedb_proof_hex),
        &hexv(&file.identity_id),
        100,
    )
    .expect("dpns by identity verify");
    check_documents(q, result);
}

#[test]
fn dashpay_profile() {
    let file = load();
    let q = query(&file, "dashpay_profile");
    let result =
        verify::verify_dashpay_profile_by_owner(&hexv(&q.grovedb_proof_hex), &hexv(&file.identity_id))
            .expect("dashpay profile verify");
    check_documents(q, result);
}

#[test]
fn dashpay_contacts() {
    let file = load();
    for (name, to_identity) in [
        ("dashpay_contacts_incoming", true),
        ("dashpay_contacts_outgoing", false),
    ] {
        let q = query(&file, name);
        let result = verify::verify_dashpay_contact_requests(
            &hexv(&q.grovedb_proof_hex),
            &hexv(&file.identity_id),
            to_identity,
            100,
        )
        .unwrap_or_else(|e| panic!("{name} verify: {e}"));
        check_documents(q, result);
    }
}

fn contested(file: &VectorFile, name: &str) -> (dash_platform_ffi::types::ContestedResult, Value) {
    let q = query(file, name);
    let label = q.query["normalized_label"].as_str().expect("normalized_label");
    let count = q.query["count"].as_u64().expect("count") as u16;
    let result = verify::verify_contested_vote_state(
        &hexv(&q.grovedb_proof_hex),
        &hexv("e668c659af66aee1e72c186dde7b5b7e0a1d712a09c40d5721f622bf53c53155"), // DPNS
        "domain",
        vec!["dash".to_string(), label.to_string()],
        count,
    )
    .unwrap_or_else(|e| panic!("{name} verify: {e}"));
    assert_eq!(
        hex::encode(result.root_hash),
        q.expected_root_hash_hex,
        "{name}: root hash"
    );
    (result, q.expected.clone())
}

#[test]
fn contested_vote_state_active() {
    let file = load();
    let (result, expected) = contested(&file, "contested_vote_state_active");
    let state = result.state;
    assert!(state.contest_found);
    assert!(!state.finished);
    assert!(!state.locked);
    assert!(state.winner.is_none());
    let expected_contenders = expected["contenders"].as_array().unwrap();
    assert_eq!(state.contenders.len(), expected_contenders.len());
    for ((identity, votes), expected) in state.contenders.iter().zip(expected_contenders) {
        assert_eq!(hex::encode(identity), expected["identity_id"].as_str().unwrap());
        assert_eq!(votes.map(u64::from), expected["votes"].as_u64());
    }
    assert_eq!(state.abstain_votes.map(u64::from), expected["abstain_votes"].as_u64());
    assert_eq!(state.lock_votes.map(u64::from), expected["lock_votes"].as_u64());
}

#[test]
fn contested_vote_state_finished() {
    let file = load();
    let (result, expected) = contested(&file, "contested_vote_state_finished");
    let state = result.state;
    assert!(state.contest_found);
    assert!(state.finished);
    assert!(!state.locked);
    assert_eq!(
        state.winner.map(hex::encode),
        expected["winner_identity_id"].as_str().map(String::from)
    );
    let expected_contenders = expected["contenders"].as_array().unwrap();
    assert_eq!(state.contenders.len(), expected_contenders.len());
    for ((identity, votes), expected) in state.contenders.iter().zip(expected_contenders) {
        assert_eq!(hex::encode(identity), expected["identity_id"].as_str().unwrap());
        assert_eq!(votes.map(u64::from), expected["votes"].as_u64());
    }
    assert_eq!(state.abstain_votes.map(u64::from), expected["abstain_votes"].as_u64());
    assert_eq!(state.lock_votes.map(u64::from), expected["lock_votes"].as_u64());
    assert!(state.finished_at_time_ms > 0);
}

#[test]
fn contested_vote_state_absent() {
    let file = load();
    let (result, _) = contested(&file, "contested_vote_state_absent");
    assert!(!result.state.contest_found);
    assert!(result.state.contenders.is_empty());
}

// A corrupted proof must never verify against the expected root.
#[test]
fn corrupted_proof_rejected() {
    let file = load();
    let q = query(&file, "identity_balance");
    let mut proof = hexv(&q.grovedb_proof_hex);
    let mid = proof.len() / 2;
    proof[mid] ^= 0x01;
    match verify::verify_identity_balance(&proof, &hexv(&file.identity_id)) {
        Err(_) => {}
        Ok(result) => {
            assert_ne!(
                hex::encode(result.root_hash),
                q.expected_root_hash_hex,
                "tampered proof must not reproduce the signed root"
            );
        }
    }
}
