// Copyright (c) 2026 The Dash Core developers
// Distributed under the MIT software license, see the accompanying
// file COPYING or http://www.opensource.org/licenses/mit-license.php.

//! Tests for the Drive per-query verifier (src/platform/drive/queries.*) and
//! the Tenderdash quorum-signature check (src/platform/drive/quorumsig.*),
//! against JSON vectors generated by the platform-drive-vectors crate
//! (github.com/PastaPastaPasta/dash-platform-test-vectors)
//! from the real dashpay/platform (v4.0.0) + grovedb (v5.0.0) +
//! rs-tenderdash-abci (v1.5.1) code.

#include <test/data/platform/drive_query_vectors.json.h>
#include <test/data/platform/quorum_sig_vectors.json.h>

#include <platform/client.h>
#include <platform/drive/queries.h>
#include <platform/drive/quorumsig.h>
#include <platform/drive/verify.h>
#include <platform/dpp/identity.h>
#include <platform/serialize.h>
#include <platform/types.h>

#include <test/util/setup_common.h>
#include <util/strencodings.h>

#include <univalue.h>

#include <boost/test/unit_test.hpp>

#include <array>
#include <optional>
#include <string>
#include <vector>

using platform::Bytes;
using platform::Identifier;
using platform::Identity;
using platform::IdentityPublicKey;
using platform::drive::BlockContext;
using platform::drive::ProofEnvelope;
using platform::drive::QuorumKeyLookup;
using platform::drive::SignDigestIntermediates;
using platform::merk::Hash256;

BOOST_FIXTURE_TEST_SUITE(platform_drive_tests, BasicTestingSetup)

namespace {

UniValue ReadJsonObject(const unsigned char* data, size_t size)
{
    UniValue v;
    BOOST_REQUIRE(v.read(std::string(data, data + size)));
    BOOST_REQUIRE(v.isObject());
    return v;
}

Bytes FromHex(const std::string& hex)
{
    const auto parsed{TryParseHex<uint8_t>(hex)};
    BOOST_REQUIRE_MESSAGE(parsed.has_value(), "invalid hex in test vector: " + hex);
    return *parsed;
}

Hash256 HashFromHex(const std::string& hex)
{
    const Bytes bytes{FromHex(hex)};
    BOOST_REQUIRE_EQUAL(bytes.size(), 32U);
    Hash256 out{};
    std::copy(bytes.begin(), bytes.end(), out.begin());
    return out;
}

Identifier IdFromHex(const std::string& hex)
{
    const Bytes bytes{FromHex(hex)};
    BOOST_REQUIRE_EQUAL(bytes.size(), 32U);
    Identifier out{};
    std::copy(bytes.begin(), bytes.end(), out.begin());
    return out;
}

//! Returns the query object with the given name, or fails the test.
UniValue FindQuery(const UniValue& doc, const std::string& name)
{
    const UniValue& queries{doc["queries"]};
    for (size_t i = 0; i < queries.size(); ++i) {
        if (queries[i]["name"].get_str() == name) return queries[i];
    }
    BOOST_FAIL("query vector not found: " + name);
    return UniValue{};
}

Bytes ProofOf(const UniValue& query) { return FromHex(query["grovedb_proof_hex"].get_str()); }

ProofEnvelope EnvelopeFromJson(const UniValue& env)
{
    ProofEnvelope out;
    out.quorum_type = static_cast<uint8_t>(env["quorum_type"].getInt<int>());
    out.quorum_hash = HashFromHex(env["quorum_hash"].get_str());
    out.block_id_hash = HashFromHex(env["block_id_hash"].get_str());
    out.round = env["round"].getInt<int>();
    const Bytes sig{FromHex(env["signature"].get_str())};
    BOOST_REQUIRE_EQUAL(sig.size(), 96U);
    std::copy(sig.begin(), sig.end(), out.signature.begin());
    return out;
}

BlockContext ContextFromJson(const UniValue& ctx)
{
    BlockContext out;
    out.height = ctx["height"].getInt<int64_t>();
    out.core_chain_locked_height = static_cast<uint32_t>(ctx["core_chain_locked_height"].getInt<int64_t>());
    out.time_ms = ctx["time_ms"].getInt<int64_t>();
    out.protocol_version = ctx["protocol_version"].getInt<int64_t>();
    out.chain_id = ctx["chain_id"].get_str();
    return out;
}

} // namespace

// ---------------------------------------------------------------------------
// Drive per-query decoding
// ---------------------------------------------------------------------------
BOOST_AUTO_TEST_CASE(identity_balance)
{
    const UniValue doc{ReadJsonObject(json_tests::drive_query_vectors, sizeof(json_tests::drive_query_vectors))};
    const Identifier id{IdFromHex(doc["identity_id"].get_str())};
    const UniValue q{FindQuery(doc, "identity_balance")};
    const Bytes proof{ProofOf(q)};

    std::optional<uint64_t> balance;
    Hash256 root{};
    std::string error;
    BOOST_REQUIRE_MESSAGE(
        platform::drive::VerifyIdentityBalance(Span<const uint8_t>(proof), id, balance, root, error),
        error);
    BOOST_REQUIRE(balance.has_value());
    BOOST_CHECK_EQUAL(*balance, q["expected"]["balance"].getInt<uint64_t>());
    BOOST_CHECK_EQUAL(HexStr(root), q["expected_root_hash_hex"].get_str());
}

BOOST_AUTO_TEST_CASE(identity_revision_and_nonce)
{
    const UniValue doc{ReadJsonObject(json_tests::drive_query_vectors, sizeof(json_tests::drive_query_vectors))};
    const Identifier id{IdFromHex(doc["identity_id"].get_str())};

    {
        const UniValue q{FindQuery(doc, "identity_revision")};
        const Bytes proof{ProofOf(q)};
        std::optional<uint64_t> revision;
        Hash256 root{};
        std::string error;
        BOOST_REQUIRE_MESSAGE(
            platform::drive::VerifyIdentityRevision(Span<const uint8_t>(proof), id, revision, root, error),
            error);
        BOOST_REQUIRE(revision.has_value());
        BOOST_CHECK_EQUAL(*revision, q["expected"]["revision"].getInt<uint64_t>());
    }
    {
        const UniValue q{FindQuery(doc, "identity_nonce")};
        const Bytes proof{ProofOf(q)};
        std::optional<uint64_t> nonce;
        Hash256 root{};
        std::string error;
        BOOST_REQUIRE_MESSAGE(
            platform::drive::VerifyIdentityNonce(Span<const uint8_t>(proof), id, nonce, root, error),
            error);
        BOOST_REQUIRE(nonce.has_value());
        BOOST_CHECK_EQUAL(*nonce, q["expected"]["nonce"].getInt<uint64_t>());
    }
    {
        const UniValue q{FindQuery(doc, "identity_contract_nonce")};
        const Bytes proof{ProofOf(q)};
        const Identifier contract{IdFromHex(q["query"]["contract_id"].get_str())};
        std::optional<uint64_t> nonce;
        Hash256 root{};
        std::string error;
        BOOST_REQUIRE_MESSAGE(platform::drive::VerifyIdentityContractNonce(
            Span<const uint8_t>(proof), id, contract, nonce, root, error), error);
        BOOST_REQUIRE(nonce.has_value());
        BOOST_CHECK_EQUAL(*nonce, q["expected"]["nonce"].getInt<uint64_t>());
    }
}

BOOST_AUTO_TEST_CASE(identity_keys)
{
    const UniValue doc{ReadJsonObject(json_tests::drive_query_vectors, sizeof(json_tests::drive_query_vectors))};
    const Identifier id{IdFromHex(doc["identity_id"].get_str())};
    const UniValue q{FindQuery(doc, "identity_keys")};
    const Bytes proof{ProofOf(q)};

    std::optional<std::vector<IdentityPublicKey>> keys;
    Hash256 root{};
    std::string error;
    BOOST_REQUIRE_MESSAGE(
        platform::drive::VerifyIdentityKeys(Span<const uint8_t>(proof), id, keys, root, error), error);
    BOOST_REQUIRE(keys.has_value());

    const UniValue& expected{q["expected"]["serialized_keys"]};
    BOOST_REQUIRE_EQUAL(keys->size(), expected.size());
    // Re-derive each key's id from its expected serialization for a spot check
    // that decoding produced the right key ids in order.
    const std::array<uint32_t, 3> expected_ids{0, 1, 2};
    for (size_t i = 0; i < keys->size(); ++i) {
        BOOST_CHECK_EQUAL((*keys)[i].id, expected_ids[i]);
    }
}

BOOST_AUTO_TEST_CASE(identity_by_public_key_hash)
{
    const UniValue doc{ReadJsonObject(json_tests::drive_query_vectors, sizeof(json_tests::drive_query_vectors))};

    {
        const UniValue q{FindQuery(doc, "identity_by_public_key_hash_present")};
        const Bytes proof{ProofOf(q)};
        const Bytes pkh_bytes{FromHex(q["query"]["public_key_hash"].get_str())};
        BOOST_REQUIRE_EQUAL(pkh_bytes.size(), 20U);
        std::array<uint8_t, 20> pkh{};
        std::copy(pkh_bytes.begin(), pkh_bytes.end(), pkh.begin());

        std::optional<Identifier> found;
        Hash256 root{};
        std::string error;
        BOOST_REQUIRE_MESSAGE(
            platform::drive::VerifyIdentityIdByPublicKeyHash(Span<const uint8_t>(proof), pkh, found, root, error),
            error);
        BOOST_REQUIRE(found.has_value());
        BOOST_CHECK_EQUAL(HexStr(*found), q["expected"]["identity_id"].get_str());
    }
    {
        const UniValue q{FindQuery(doc, "identity_by_public_key_hash_absent")};
        const Bytes proof{ProofOf(q)};
        const Bytes pkh_bytes{FromHex(q["query"]["public_key_hash"].get_str())};
        std::array<uint8_t, 20> pkh{};
        std::copy(pkh_bytes.begin(), pkh_bytes.end(), pkh.begin());

        std::optional<Identifier> found;
        Hash256 root{};
        std::string error;
        BOOST_REQUIRE_MESSAGE(
            platform::drive::VerifyIdentityIdByPublicKeyHash(Span<const uint8_t>(proof), pkh, found, root, error),
            error);
        BOOST_CHECK(!found.has_value()); // proven absent
    }
}

BOOST_AUTO_TEST_CASE(full_identity)
{
    const UniValue doc{ReadJsonObject(json_tests::drive_query_vectors, sizeof(json_tests::drive_query_vectors))};
    const Identifier id{IdFromHex(doc["identity_id"].get_str())};
    const Bytes balance_proof{ProofOf(FindQuery(doc, "identity_balance"))};
    const Bytes revision_proof{ProofOf(FindQuery(doc, "identity_revision"))};
    const Bytes keys_proof{ProofOf(FindQuery(doc, "identity_keys"))};

    std::optional<Identity> identity;
    Hash256 root{};
    std::string error;
    BOOST_REQUIRE_MESSAGE(
        platform::drive::VerifyFullIdentity(Span<const uint8_t>(balance_proof),
                                            Span<const uint8_t>(revision_proof),
                                            Span<const uint8_t>(keys_proof), id, identity, root, error),
        error);
    BOOST_REQUIRE(identity.has_value());
    BOOST_CHECK(identity->id == id);
    BOOST_CHECK_EQUAL(identity->balance, FindQuery(doc, "identity_balance")["expected"]["balance"].getInt<uint64_t>());
    BOOST_CHECK_EQUAL(identity->revision, FindQuery(doc, "identity_revision")["expected"]["revision"].getInt<uint64_t>());
    BOOST_CHECK_EQUAL(identity->public_keys.size(), 3U);
}

BOOST_AUTO_TEST_CASE(document_index_proofs)
{
    const UniValue doc{ReadJsonObject(json_tests::drive_query_vectors, sizeof(json_tests::drive_query_vectors))};
    const Identifier id{IdFromHex(doc["identity_id"].get_str())};
    auto check = [&](const std::string& name, const auto& verify) {
        const UniValue query{FindQuery(doc, name)};
        const Bytes proof{ProofOf(query)};
        std::vector<Bytes> documents;
        Hash256 root{};
        std::string error;
        BOOST_REQUIRE_MESSAGE(verify(Span<const uint8_t>{proof}, documents, root, error), name + ": " + error);
        const UniValue& expected{query["expected"]["documents"]};
        BOOST_REQUIRE_EQUAL(documents.size(), expected.size());
        for (size_t i = 0; i < documents.size(); ++i) BOOST_CHECK_EQUAL(HexStr(documents[i]), expected[i].get_str());
        BOOST_CHECK_EQUAL(HexStr(root), query["expected_root_hash_hex"].get_str());
    };

    check("dpns_exact", [](auto proof, auto& documents, auto& root, auto& error) {
        return platform::drive::VerifyDpnsNameExact(proof, "alice", documents, root, error);
    });
    check("dpns_prefix", [](auto proof, auto& documents, auto& root, auto& error) {
        return platform::drive::VerifyDpnsNamePrefix(proof, "ali", 25, documents, root, error);
    });
    check("dpns_by_identity", [&id](auto proof, auto& documents, auto& root, auto& error) {
        return platform::drive::VerifyDpnsNamesByIdentity(proof, id, 100, documents, root, error);
    });
    check("dashpay_profile", [&id](auto proof, auto& documents, auto& root, auto& error) {
        return platform::drive::VerifyDashPayProfileByOwner(proof, id, documents, root, error);
    });
    check("dashpay_contacts_incoming", [&id](auto proof, auto& documents, auto& root, auto& error) {
        return platform::drive::VerifyDashPayContactRequests(proof, id, true, 100, documents, root, error);
    });
    check("dashpay_contacts_outgoing", [&id](auto proof, auto& documents, auto& root, auto& error) {
        return platform::drive::VerifyDashPayContactRequests(proof, id, false, 100, documents, root, error);
    });
}

// ---------------------------------------------------------------------------
// Quorum signature: digest intermediates + verification verdicts
// ---------------------------------------------------------------------------
BOOST_AUTO_TEST_CASE(quorum_sig_digest_intermediates)
{
    const UniValue doc{ReadJsonObject(json_tests::quorum_sig_vectors, sizeof(json_tests::quorum_sig_vectors))};
    const UniValue& vectors{doc["vectors"]};
    // The first vector ("valid") carries the intermediate hex to check against.
    const UniValue valid{vectors[0]};
    BOOST_REQUIRE_EQUAL(valid["name"].get_str(), "valid");

    const Hash256 app_hash{HashFromHex(valid["app_hash"].get_str())};
    const ProofEnvelope env{EnvelopeFromJson(valid["envelope"])};
    const BlockContext ctx{ContextFromJson(valid["block_context"])};

    const SignDigestIntermediates inter{platform::drive::ComputeSignDigest(app_hash, env, ctx)};
    const UniValue& expected{valid["intermediates"]};

    BOOST_CHECK_EQUAL(HexStr(inter.request_id), expected["request_id"].get_str());
    BOOST_CHECK_EQUAL(HexStr(inter.state_id_bytes), expected["state_id_bytes"].get_str());
    BOOST_CHECK_EQUAL(HexStr(inter.state_id_hash), expected["state_id_hash"].get_str());
    BOOST_CHECK_EQUAL(HexStr(inter.canonical_vote_bytes), expected["canonical_vote_bytes"].get_str());
    BOOST_CHECK_EQUAL(HexStr(inter.vote_hash), expected["vote_hash"].get_str());
    BOOST_CHECK_EQUAL(HexStr(inter.sign_digest), expected["sign_digest"].get_str());
}

BOOST_AUTO_TEST_CASE(quorum_sig_verdicts)
{
    const UniValue doc{ReadJsonObject(json_tests::quorum_sig_vectors, sizeof(json_tests::quorum_sig_vectors))};
    const UniValue& vectors{doc["vectors"]};
    BOOST_REQUIRE(vectors.size() >= 2);

    for (size_t i = 0; i < vectors.size(); ++i) {
        const UniValue v{vectors[i]};
        const std::string name{v["name"].get_str()};
        const Hash256 app_hash{HashFromHex(v["app_hash"].get_str())};
        const ProofEnvelope env{EnvelopeFromJson(v["envelope"])};
        const BlockContext ctx{ContextFromJson(v["block_context"])};
        const Bytes pubkey{FromHex(v["quorum_public_key"].get_str())};
        const bool expected_valid{v["expected_valid"].get_bool()};

        std::string error;
        const bool ok{platform::drive::VerifyQuorumSig(app_hash, env, ctx, pubkey, error)};
        BOOST_CHECK_MESSAGE(ok == expected_valid,
                            "vector '" + name + "' expected valid=" + (expected_valid ? "true" : "false") +
                                " got=" + (ok ? "true" : "false") + " error=" + error);
    }
}

BOOST_AUTO_TEST_CASE(quorum_key_matches_dapi_hash_byte_order)
{
    platform::QuorumKey key;
    for (size_t i = 0; i < key.quorum_hash.size(); ++i) {
        key.quorum_hash.begin()[i] = static_cast<uint8_t>(i);
    }

    Hash256 proof_hash{};
    for (size_t i = 0; i < proof_hash.size(); ++i) {
        proof_hash[i] = static_cast<uint8_t>(proof_hash.size() - 1 - i);
    }
    BOOST_CHECK(key.matchesProofHash(proof_hash));

    proof_hash[0] ^= 1;
    BOOST_CHECK(!key.matchesProofHash(proof_hash));
}

// End-to-end: a valid grovedb proof + quorum key produces a decoded, bound
// result; a tampered root breaks the quorum-signature binding.
BOOST_AUTO_TEST_CASE(quorum_sig_binds_grovedb_root)
{
    const UniValue qdoc{ReadJsonObject(json_tests::quorum_sig_vectors, sizeof(json_tests::quorum_sig_vectors))};
    const UniValue valid{qdoc["vectors"][0]};
    const ProofEnvelope env{EnvelopeFromJson(valid["envelope"])};
    const BlockContext ctx{ContextFromJson(valid["block_context"])};
    const Bytes pubkey{FromHex(valid["quorum_public_key"].get_str())};

    const UniValue ddoc{ReadJsonObject(json_tests::drive_query_vectors, sizeof(json_tests::drive_query_vectors))};
    const Identifier id{IdFromHex(ddoc["identity_id"].get_str())};
    const Bytes balance_proof{ProofOf(FindQuery(ddoc, "identity_balance"))};

    // The quorum vectors sign the balance proof's grovedb root as app_hash.
    const QuorumKeyLookup lookup{[&](uint8_t qt, const Hash256& qh) -> std::optional<std::vector<uint8_t>> {
        if (qt == env.quorum_type && qh == env.quorum_hash) return pubkey;
        return std::nullopt;
    }};

    std::optional<uint64_t> balance;
    std::string error;
    BOOST_CHECK_MESSAGE(
        platform::drive::VerifyAndDecodeIdentityBalance(Span<const uint8_t>(balance_proof), env, ctx,
                                                        id, lookup, balance, error),
        error);
    BOOST_REQUIRE(balance.has_value());

    // An unknown quorum (lookup returns nullopt) must fail the binding.
    const QuorumKeyLookup empty_lookup{[](uint8_t, const Hash256&) { return std::nullopt; }};
    std::optional<uint64_t> balance2;
    std::string error2;
    BOOST_CHECK(!platform::drive::VerifyAndDecodeIdentityBalance(
        Span<const uint8_t>(balance_proof), env, ctx, id, empty_lookup, balance2, error2));
}

BOOST_AUTO_TEST_SUITE_END()
