/*
 * GroveDB C FFI - Foreign Function Interface for GroveDB
 *
 * This header provides C bindings to GroveDB, a hierarchical authenticated
 * data structure optimized for efficient secondary index queries and
 * cryptographic proofs.
 *
 * Memory Management:
 * - All handles (grovedb_t*, grovedb_transaction_t*, etc.) are owned by Rust
 * - Caller must free returned data using appropriate grovedb_free_* functions
 * - Input ByteBuffer data must remain valid for the duration of the call
 *
 * Error Handling:
 * - Functions that can fail take a GroveDbError* output parameter
 * - Check error->code for GROVEDB_ERROR_OK (0) on success
 * - Free error messages with grovedb_free_string()
 *
 * Thread Safety:
 * - GroveDb handle can be shared across threads (uses internal synchronization)
 * - Transaction handles should be used by a single thread at a time
 */


#ifndef GROVEDB_FFI_H
#define GROVEDB_FFI_H

/* Warning: this file is autogenerated by cbindgen. Don't modify manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Maximum number of path segments allowed.
 * This prevents excessive memory allocation from malformed input.
 */
#define MAX_PATH_SEGMENTS 256

/**
 * Maximum size of a single path segment (10 MB).
 * This prevents excessive memory allocation from malformed input.
 */
#define MAX_SEGMENT_SIZE 10000000

/**
 * Operation type for batch operations.
 */
typedef enum BatchOpType {
    /**
     * Insert only if the key doesn't exist
     */
    BATCH_OP_TYPE_INSERT_ONLY = 0,
    /**
     * Insert or replace if the key exists
     */
    BATCH_OP_TYPE_INSERT_OR_REPLACE = 1,
    /**
     * Replace only if the key exists
     */
    BATCH_OP_TYPE_REPLACE = 2,
    /**
     * Delete an element
     */
    BATCH_OP_TYPE_DELETE = 3,
    /**
     * Delete a tree (non-sum tree)
     */
    BATCH_OP_TYPE_DELETE_TREE = 4,
    /**
     * Delete a sum tree
     */
    BATCH_OP_TYPE_DELETE_SUM_TREE = 5,
} BatchOpType;

/**
 * Element type enumeration matching GroveDB's Element variants.
 */
typedef enum GroveDbElementType {
    /**
     * An item containing arbitrary bytes
     */
    GROVE_DB_ELEMENT_TYPE_ITEM = 0,
    /**
     * A reference to another element
     */
    GROVE_DB_ELEMENT_TYPE_REFERENCE = 1,
    /**
     * A subtree
     */
    GROVE_DB_ELEMENT_TYPE_TREE = 2,
    /**
     * A sum item (i64 value for aggregation)
     */
    GROVE_DB_ELEMENT_TYPE_SUM_ITEM = 3,
    /**
     * A sum tree (tree that tracks sum of SumItems)
     */
    GROVE_DB_ELEMENT_TYPE_SUM_TREE = 4,
    /**
     * A big sum tree (tree that tracks i128 sum)
     */
    GROVE_DB_ELEMENT_TYPE_BIG_SUM_TREE = 5,
    /**
     * A count tree (tree that tracks count)
     */
    GROVE_DB_ELEMENT_TYPE_COUNT_TREE = 6,
    /**
     * A count sum tree (tree that tracks both count and sum)
     */
    GROVE_DB_ELEMENT_TYPE_COUNT_SUM_TREE = 7,
} GroveDbElementType;

/**
 * Error codes returned by FFI functions.
 *
 * Check for `GROVEDB_ERROR_OK` (0) to confirm success.
 */
typedef enum GroveDbErrorCode {
    /**
     * Operation succeeded
     */
    GROVE_DB_ERROR_CODE_OK = 0,
    /**
     * Null pointer passed where non-null was expected
     */
    GROVE_DB_ERROR_CODE_NULL_POINTER = 1,
    /**
     * Memory allocation failed
     */
    GROVE_DB_ERROR_CODE_ALLOCATION_ERROR = 2,
    /**
     * Internal error
     */
    GROVE_DB_ERROR_CODE_INTERNAL_ERROR = 3,
    /**
     * Operation not supported
     */
    GROVE_DB_ERROR_CODE_NOT_SUPPORTED = 4,
    /**
     * Invalid input provided
     */
    GROVE_DB_ERROR_CODE_INVALID_INPUT = 5,
    /**
     * Invalid parameter
     */
    GROVE_DB_ERROR_CODE_INVALID_PARAMETER = 6,
    /**
     * Missing parameter
     */
    GROVE_DB_ERROR_CODE_MISSING_PARAMETER = 7,
    /**
     * Database has been closed
     */
    GROVE_DB_ERROR_CODE_DATABASE_CLOSED = 8,
    /**
     * Path not found in database
     */
    GROVE_DB_ERROR_CODE_PATH_NOT_FOUND = 10,
    /**
     * Key not found at path
     */
    GROVE_DB_ERROR_CODE_PATH_KEY_NOT_FOUND = 11,
    /**
     * Parent layer not found
     */
    GROVE_DB_ERROR_CODE_PATH_PARENT_LAYER_NOT_FOUND = 12,
    /**
     * Invalid path
     */
    GROVE_DB_ERROR_CODE_INVALID_PATH = 13,
    /**
     * Invalid parent layer path
     */
    GROVE_DB_ERROR_CODE_INVALID_PARENT_LAYER_PATH = 14,
    /**
     * Corrupted path
     */
    GROVE_DB_ERROR_CODE_CORRUPTED_PATH = 15,
    /**
     * Cyclic reference detected
     */
    GROVE_DB_ERROR_CODE_CYCLIC_REFERENCE = 20,
    /**
     * Reference hop limit exceeded
     */
    GROVE_DB_ERROR_CODE_REFERENCE_LIMIT = 21,
    /**
     * Missing reference
     */
    GROVE_DB_ERROR_CODE_MISSING_REFERENCE = 22,
    /**
     * Corrupted reference path not found
     */
    GROVE_DB_ERROR_CODE_CORRUPTED_REFERENCE_PATH_NOT_FOUND = 23,
    /**
     * Corrupted reference path key not found
     */
    GROVE_DB_ERROR_CODE_CORRUPTED_REFERENCE_PATH_KEY_NOT_FOUND = 24,
    /**
     * Corrupted data detected
     */
    GROVE_DB_ERROR_CODE_CORRUPTED_DATA = 30,
    /**
     * Corrupted storage
     */
    GROVE_DB_ERROR_CODE_CORRUPTED_STORAGE = 31,
    /**
     * Storage/IO error
     */
    GROVE_DB_ERROR_CODE_STORAGE_ERROR = 32,
    /**
     * Wrong element type
     */
    GROVE_DB_ERROR_CODE_WRONG_ELEMENT_TYPE = 33,
    /**
     * Invalid query
     */
    GROVE_DB_ERROR_CODE_INVALID_QUERY = 40,
    /**
     * Invalid proof
     */
    GROVE_DB_ERROR_CODE_INVALID_PROOF = 41,
    /**
     * Override not allowed
     */
    GROVE_DB_ERROR_CODE_OVERRIDE_NOT_ALLOWED = 50,
    /**
     * Deleting non-empty tree
     */
    GROVE_DB_ERROR_CODE_DELETING_NON_EMPTY_TREE = 51,
    /**
     * Invalid batch operation
     */
    GROVE_DB_ERROR_CODE_INVALID_BATCH_OPERATION = 52,
    /**
     * Delete up tree stop height error
     */
    GROVE_DB_ERROR_CODE_DELETE_UP_TREE_STOP_HEIGHT_ERROR = 53,
    /**
     * Clearing tree with subtrees not allowed
     */
    GROVE_DB_ERROR_CODE_CLEARING_TREE_WITH_SUBTREES_NOT_ALLOWED = 54,
    /**
     * Version mismatch or error
     */
    GROVE_DB_ERROR_CODE_VERSION_ERROR = 60,
    /**
     * Merk tree error
     */
    GROVE_DB_ERROR_CODE_MERK_ERROR = 70,
    /**
     * Invalid code execution
     */
    GROVE_DB_ERROR_CODE_INVALID_CODE_EXECUTION = 80,
    /**
     * Corrupted code execution
     */
    GROVE_DB_ERROR_CODE_CORRUPTED_CODE_EXECUTION = 81,
    /**
     * Just-in-time element flags client error
     */
    GROVE_DB_ERROR_CODE_JUST_IN_TIME_ELEMENT_FLAGS_CLIENT_ERROR = 90,
    /**
     * Split removal bytes client error
     */
    GROVE_DB_ERROR_CODE_SPLIT_REMOVAL_BYTES_CLIENT_ERROR = 91,
    /**
     * Client returned non-client error
     */
    GROVE_DB_ERROR_CODE_CLIENT_RETURNED_NON_CLIENT_ERROR = 92,
    /**
     * Unknown/unhandled error
     */
    GROVE_DB_ERROR_CODE_UNKNOWN = 255,
} GroveDbErrorCode;

/**
 * Query item type enumeration.
 */
typedef enum QueryItemType {
    /**
     * Single key lookup
     */
    QUERY_ITEM_TYPE_KEY = 0,
    /**
     * Range [start, end)
     */
    QUERY_ITEM_TYPE_RANGE = 1,
    /**
     * Range [start, end]
     */
    QUERY_ITEM_TYPE_RANGE_INCLUSIVE = 2,
    /**
     * Full range (..)
     */
    QUERY_ITEM_TYPE_RANGE_FULL = 3,
    /**
     * Range [start, ..)
     */
    QUERY_ITEM_TYPE_RANGE_FROM = 4,
    /**
     * Range (.., end)
     */
    QUERY_ITEM_TYPE_RANGE_TO = 5,
    /**
     * Range (.., end]
     */
    QUERY_ITEM_TYPE_RANGE_TO_INCLUSIVE = 6,
    /**
     * Range (start, ..)
     */
    QUERY_ITEM_TYPE_RANGE_AFTER = 7,
    /**
     * Range (start, end)
     */
    QUERY_ITEM_TYPE_RANGE_AFTER_TO = 8,
    /**
     * Range (start, end]
     */
    QUERY_ITEM_TYPE_RANGE_AFTER_TO_INCLUSIVE = 9,
} QueryItemType;

/**
 * Reference path type enumeration.
 */
typedef enum ReferencePathTypeTag {
    /**
     * Absolute path reference
     */
    REFERENCE_PATH_TYPE_TAG_ABSOLUTE_PATH = 0,
    /**
     * Upstream from root height
     */
    REFERENCE_PATH_TYPE_TAG_UPSTREAM_ROOT_HEIGHT = 1,
    /**
     * Upstream from root height with parent path addition
     */
    REFERENCE_PATH_TYPE_TAG_UPSTREAM_ROOT_HEIGHT_WITH_PARENT_PATH_ADDITION = 2,
    /**
     * Upstream from element height
     */
    REFERENCE_PATH_TYPE_TAG_UPSTREAM_FROM_ELEMENT_HEIGHT = 3,
    /**
     * Cousin reference (sibling tree swap)
     */
    REFERENCE_PATH_TYPE_TAG_COUSIN = 4,
    /**
     * Removed cousin reference
     */
    REFERENCE_PATH_TYPE_TAG_REMOVED_COUSIN = 5,
    /**
     * Sibling reference (same tree)
     */
    REFERENCE_PATH_TYPE_TAG_SIBLING = 6,
} ReferencePathTypeTag;

/**
 * Opaque handle to a batch builder.
 */
typedef struct BatchHandle {
    uint8_t _private[0];
} BatchHandle;

/**
 * Detailed error information returned by FFI functions.
 *
 * # Memory Management
 * If `message` is non-null, the caller must free it with `grovedb_free_string()`.
 */
typedef struct GroveDbError {
    /**
     * Error code indicating the type of error
     */
    enum GroveDbErrorCode code;
    /**
     * Null-terminated error message (may be null)
     */
    char *message;
} GroveDbError;

/**
 * A borrowed byte buffer (caller owns the data, must remain valid during call).
 *
 * This is used for input parameters where the FFI function only needs to read
 * the data during the call.
 */
typedef struct ByteBuffer {
    /**
     * Pointer to the data (may be null for empty/none)
     */
    const uint8_t *data;
    /**
     * Length of the data in bytes
     */
    size_t len;
} ByteBuffer;

/**
 * A path in GroveDB represented as an array of byte buffer segments.
 *
 * This is used for input paths (borrowed data).
 */
typedef struct GroveDbPath {
    /**
     * Array of path segments
     */
    const struct ByteBuffer *segments;
    /**
     * Number of segments in the path
     */
    size_t count;
} GroveDbPath;

/**
 * An owned byte buffer (caller must free with `grovedb_free_byte_buffer`).
 *
 * This is used for output data that the FFI function allocates and returns
 * to the caller.
 */
typedef struct OwnedByteBuffer {
    /**
     * Pointer to the data (may be null if allocation failed or empty)
     */
    uint8_t *data;
    /**
     * Length of the data in bytes
     */
    size_t len;
    /**
     * Capacity of the allocation (for proper deallocation)
     */
    size_t capacity;
} OwnedByteBuffer;

/**
 * An owned path (caller must free with `grovedb_free_path_owned`).
 */
typedef struct GroveDbPathOwned {
    /**
     * Array of owned path segments
     */
    struct OwnedByteBuffer *segments;
    /**
     * Number of segments in the path
     */
    size_t count;
    /**
     * Capacity of the segments array (for proper deallocation)
     */
    size_t capacity;
} GroveDbPathOwned;

/**
 * C-compatible representation of a GroveDB element.
 *
 * The interpretation of fields depends on `element_type`:
 *
 * - `Item`: `value` contains the item data
 * - `Reference`: `reference_path_type`, `reference_path`, and optionally `reference_hop_count`
 * - `Tree`: `value` may contain the root key (usually empty for new trees)
 * - `SumItem`: `sum_value` contains the i64 value
 * - `SumTree`: `sum_value` contains the tree's sum
 * - `BigSumTree`: `big_sum_value_low` and `big_sum_value_high` form an i128
 * - `CountTree`: `count_value` contains the count
 * - `CountSumTree`: `sum_value` and `count_value` both used
 *
 * Free with `grovedb_free_element()` when done.
 */
typedef struct GroveDbElement {
    /**
     * The type of this element
     */
    enum GroveDbElementType element_type;
    /**
     * For Item: the item data
     * For Tree/SumTree/etc: optional root key
     */
    struct OwnedByteBuffer value;
    /**
     * Optional element flags
     */
    struct OwnedByteBuffer flags;
    /**
     * For SumItem/SumTree/CountSumTree: the sum value (i64)
     */
    int64_t sum_value;
    /**
     * For BigSumTree: low 64 bits of i128
     */
    uint64_t big_sum_value_low;
    /**
     * For BigSumTree: high 64 bits of i128 (including sign)
     */
    int64_t big_sum_value_high;
    /**
     * For CountTree/CountSumTree: the count value (u64)
     */
    uint64_t count_value;
    /**
     * For Reference: the reference path type tag
     */
    enum ReferencePathTypeTag reference_path_type;
    /**
     * For Reference: the reference path
     */
    struct GroveDbPathOwned reference_path;
    /**
     * For Reference: max hops (0 means no limit)
     */
    uint8_t reference_hop_count;
    /**
     * For Reference: whether hop count is set
     */
    bool reference_hop_count_set;
} GroveDbElement;

/**
 * Opaque handle to a GroveDb instance.
 *
 * This handle stores an ID that maps to the actual database wrapper in the
 * global handle table. This design eliminates race conditions between
 * operations and close by ensuring all access goes through the mutex-protected
 * table.
 *
 * Obtain with `grovedb_open()`, free with `grovedb_close()`.
 */
typedef struct grovedb_t {
    /**
     * The handle ID that maps to an entry in HANDLE_TABLE
     */
    uint64_t id;
} grovedb_t;

/**
 * Opaque handle representing a transaction ID.
 *
 * This is actually just a wrapper around a u64 transaction ID.
 * Obtain with `grovedb_start_transaction()`, use `grovedb_commit_transaction()`
 * or `grovedb_rollback_transaction()` to finish.
 */
typedef struct grovedb_transaction_t {
    /**
     * The transaction ID (not actually opaque, but presented as such to C)
     */
    uint64_t id;
} grovedb_transaction_t;

/**
 * Options for insert operations.
 */
typedef struct InsertOptions {
    /**
     * If true, fail if key already exists (default: false)
     */
    bool validate_insertion_does_not_override;
    /**
     * If true, fail if overriding a tree element (default: true)
     */
    bool validate_insertion_does_not_override_tree;
    /**
     * If true, base root storage operations are free (default: true)
     */
    bool base_root_storage_is_free;
} InsertOptions;

/**
 * Options for delete operations.
 */
typedef struct DeleteOptions {
    /**
     * If true, allow deleting non-empty trees (default: false)
     */
    bool allow_deleting_non_empty_trees;
    /**
     * If true, return error when deleting non-empty trees (default: true)
     */
    bool deleting_non_empty_trees_returns_error;
    /**
     * If true, base root storage operations are free (default: true)
     */
    bool base_root_storage_is_free;
    /**
     * If true, validate tree at path exists (default: false)
     */
    bool validate_tree_at_path_exists;
} DeleteOptions;

/**
 * Opaque handle to a PathQuery builder.
 *
 * Note: This handle actually stores a `PathQueryBuilder` internally, not a `PathQuery`.
 * The builder is converted to a `PathQuery` when the query is executed.
 *
 * Obtain with `grovedb_path_query_new()`, free with `grovedb_free_path_query()`.
 */
typedef struct grovedb_path_query_t {
    uint8_t _private[0];
} grovedb_path_query_t;

/**
 * A single query result element.
 */
typedef struct QueryResultElement {
    /**
     * The path to the element (may be null for element-only results)
     */
    struct GroveDbPathOwned path;
    /**
     * The key of the element (may be null for element-only results)
     */
    struct OwnedByteBuffer key;
    /**
     * The element (may be null if not present)
     */
    struct GroveDbElement *element;
    /**
     * Whether the element is present
     */
    bool has_element;
} QueryResultElement;

/**
 * Query results returned from query operations.
 *
 * Free with `grovedb_free_query_results()`.
 */
typedef struct QueryResults {
    /**
     * Array of result elements
     */
    struct QueryResultElement *elements;
    /**
     * Number of elements in the array
     */
    size_t count;
    /**
     * Capacity of the elements array (for proper deallocation)
     */
    size_t capacity;
    /**
     * Number of elements skipped (due to offset)
     */
    uint16_t skipped;
} QueryResults;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Create a new batch operation builder.
 *
 * # Arguments
 *
 * * `error_out` - Pointer to receive error details (may be null)
 *
 * # Returns
 *
 * A handle to the batch builder, or null on error.
 * The caller must apply or free the batch with `grovedb_apply_batch` or `grovedb_free_batch`.
 */
struct BatchHandle *grovedb_batch_new(struct GroveDbError *error_out);

/**
 * Add an insert operation to the batch.
 *
 * # Arguments
 *
 * * `batch` - Batch handle
 * * `path` - Path to the subtree
 * * `key` - Key within the subtree
 * * `element` - Element to insert (borrowed, caller retains ownership)
 * * `op_type` - Type of insert operation (InsertOnly, InsertOrReplace, Replace)
 * * `error_out` - Pointer to receive error details (may be null)
 *
 * # Returns
 *
 * `true` on success, `false` on error. Element is always retained by caller.
 */
bool grovedb_batch_add_insert(struct BatchHandle *batch,
                              const struct GroveDbPath *path,
                              struct ByteBuffer key,
                              const struct GroveDbElement *element,
                              enum BatchOpType op_type,
                              struct GroveDbError *error_out);

/**
 * Add a delete operation to the batch.
 *
 * # Arguments
 *
 * * `batch` - Batch handle
 * * `path` - Path to the subtree
 * * `key` - Key to delete
 * * `error_out` - Pointer to receive error details (may be null)
 *
 * # Returns
 *
 * `true` on success, `false` on error.
 */
bool grovedb_batch_add_delete(struct BatchHandle *batch,
                              const struct GroveDbPath *path,
                              struct ByteBuffer key,
                              struct GroveDbError *error_out);

/**
 * Add a delete tree operation to the batch.
 *
 * # Arguments
 *
 * * `batch` - Batch handle
 * * `path` - Path to the subtree containing the tree
 * * `key` - Key of the tree to delete
 * * `is_sum_tree` - Whether the tree is a sum tree
 * * `error_out` - Pointer to receive error details (may be null)
 *
 * # Returns
 *
 * `true` on success, `false` on error.
 */
bool grovedb_batch_add_delete_tree(struct BatchHandle *batch,
                                   const struct GroveDbPath *path,
                                   struct ByteBuffer key,
                                   bool is_sum_tree,
                                   struct GroveDbError *error_out);

/**
 * Get the number of operations in the batch.
 *
 * # Arguments
 *
 * * `batch` - Batch handle
 *
 * # Returns
 *
 * The number of operations, or 0 if batch is null.
 */
uintptr_t grovedb_batch_count(const struct BatchHandle *batch);

/**
 * Apply a batch of operations atomically.
 *
 * This function consumes and frees the batch handle.
 *
 * # Arguments
 *
 * * `handle` - Database handle
 * * `batch` - Batch handle (consumed, do not use after this call)
 * * `transaction` - Optional transaction handle
 * * `error_out` - Pointer to receive error details (may be null)
 *
 * # Returns
 *
 * `true` on success, `false` on error.
 *
 * # Safety
 *
 * * `handle` must be a valid database handle
 * * `batch` must be a valid batch handle and will be freed
 */
bool grovedb_apply_batch(struct grovedb_t *handle,
                         struct BatchHandle *batch,
                         const struct grovedb_transaction_t *transaction,
                         struct GroveDbError *error_out);

/**
 * Free a batch handle without applying it.
 *
 * Use this to discard a batch that was started but shouldn't be applied.
 *
 * # Arguments
 *
 * * `batch` - Batch handle (may be null, which is a no-op)
 *
 * # Safety
 *
 * * `batch` must have been returned by `grovedb_batch_new()`
 * * `batch` must not be used after this call
 */
void grovedb_free_batch(struct BatchHandle *batch);

/**
 * Open or create a GroveDB at the specified path.
 *
 * # Arguments
 *
 * * `path` - Null-terminated string path to the database directory
 * * `error_out` - Pointer to receive error details (may be null)
 *
 * # Returns
 *
 * A handle to the opened database, or null on error.
 * The caller must close the database with `grovedb_close()` when done.
 *
 * # Safety
 *
 * * `path` must be a valid null-terminated UTF-8 string
 */
struct grovedb_t *grovedb_open(const char *path, struct GroveDbError *error_out);

/**
 * Close a GroveDB handle and free all associated resources.
 *
 * This will also abort any uncommitted transactions.
 *
 * # Thread Safety
 *
 * Calling this function concurrently with other operations on the same handle
 * is undefined behavior. The caller must ensure proper synchronization.
 *
 * # Arguments
 *
 * * `handle` - Handle to close (may be null, which is a no-op)
 *
 * # Safety
 *
 * * `handle` must have been returned by `grovedb_open()`
 * * `handle` must not be used after this call
 * * `handle` must not be used concurrently with this call
 */
void grovedb_close(struct grovedb_t *handle);

/**
 * Flush all pending writes to disk.
 *
 * # Arguments
 *
 * * `handle` - Database handle
 * * `error_out` - Pointer to receive error details (may be null)
 *
 * # Returns
 *
 * `true` on success, `false` on error.
 *
 * # Safety
 *
 * * `handle` must be a valid database handle
 */
bool grovedb_flush(const struct grovedb_t *handle, struct GroveDbError *error_out);

/**
 * Get the root hash of the database.
 *
 * # Arguments
 *
 * * `handle` - Database handle
 * * `transaction` - Optional transaction handle (may be null for no transaction)
 * * `hash_out` - Pointer to 32-byte buffer to receive the hash
 * * `error_out` - Pointer to receive error details (may be null)
 *
 * # Returns
 *
 * `true` on success, `false` on error.
 *
 * # Safety
 *
 * * `handle` must be a valid database handle
 * * `hash_out` must point to at least 32 bytes of writable memory
 */
bool grovedb_root_hash(const struct grovedb_t *handle,
                       const struct grovedb_transaction_t *transaction,
                       uint8_t (*hash_out)[32],
                       struct GroveDbError *error_out);

/**
 * Insert an element at the specified path and key.
 *
 * # Arguments
 *
 * * `handle` - Database handle
 * * `path` - Path to the subtree
 * * `key` - Key within the subtree
 * * `element` - Element to insert
 * * `options` - Insert options (may be null for defaults)
 * * `transaction` - Optional transaction handle (may be null)
 * * `error_out` - Pointer to receive error details (may be null)
 *
 * # Returns
 *
 * `true` on success, `false` on error.
 *
 * # Safety
 *
 * * All pointers must be valid or null where allowed
 * * `path` segments and `key` data must remain valid during the call
 */
bool grovedb_insert(const struct grovedb_t *handle,
                    const struct GroveDbPath *path,
                    struct ByteBuffer key,
                    const struct GroveDbElement *element,
                    const struct InsertOptions *options,
                    const struct grovedb_transaction_t *transaction,
                    struct GroveDbError *error_out);

/**
 * Get an element at the specified path and key.
 *
 * # Arguments
 *
 * * `handle` - Database handle
 * * `path` - Path to the subtree
 * * `key` - Key within the subtree
 * * `transaction` - Optional transaction handle (may be null)
 * * `error_out` - Pointer to receive error details (may be null)
 *
 * # Returns
 *
 * The element if found, or null on error. Caller must free with `grovedb_free_element()`.
 *
 * # Safety
 *
 * * All pointers must be valid or null where allowed
 */
struct GroveDbElement *grovedb_get(const struct grovedb_t *handle,
                                   const struct GroveDbPath *path,
                                   struct ByteBuffer key,
                                   const struct grovedb_transaction_t *transaction,
                                   struct GroveDbError *error_out);

/**
 * Delete an element at the specified path and key.
 *
 * # Arguments
 *
 * * `handle` - Database handle
 * * `path` - Path to the subtree
 * * `key` - Key within the subtree
 * * `options` - Delete options (may be null for defaults)
 * * `transaction` - Optional transaction handle (may be null)
 * * `error_out` - Pointer to receive error details (may be null)
 *
 * # Returns
 *
 * `true` on success, `false` on error.
 *
 * # Safety
 *
 * * All pointers must be valid or null where allowed
 */
bool grovedb_delete(const struct grovedb_t *handle,
                    const struct GroveDbPath *path,
                    struct ByteBuffer key,
                    const struct DeleteOptions *options,
                    const struct grovedb_transaction_t *transaction,
                    struct GroveDbError *error_out);

/**
 * Create a new Item element.
 *
 * # Arguments
 *
 * * `data` - The item data
 * * `flags` - Optional element flags (may be null/empty)
 *
 * # Returns
 *
 * A new element. Caller must free with `grovedb_free_element()`.
 *
 * # Safety
 *
 * * `data` must be valid during the call
 */
struct GroveDbElement *grovedb_element_new_item(struct ByteBuffer data, struct ByteBuffer flags);

/**
 * Create a new empty Tree element.
 *
 * # Arguments
 *
 * * `flags` - Optional element flags (may be null/empty)
 *
 * # Returns
 *
 * A new element. Caller must free with `grovedb_free_element()`.
 */
struct GroveDbElement *grovedb_element_new_tree(struct ByteBuffer flags);

/**
 * Create a new SumItem element.
 *
 * # Arguments
 *
 * * `value` - The sum value (i64)
 * * `flags` - Optional element flags (may be null/empty)
 *
 * # Returns
 *
 * A new element. Caller must free with `grovedb_free_element()`.
 */
struct GroveDbElement *grovedb_element_new_sum_item(int64_t value, struct ByteBuffer flags);

/**
 * Create a new empty SumTree element.
 *
 * # Arguments
 *
 * * `flags` - Optional element flags (may be null/empty)
 *
 * # Returns
 *
 * A new element. Caller must free with `grovedb_free_element()`.
 */
struct GroveDbElement *grovedb_element_new_sum_tree(struct ByteBuffer flags);

/**
 * Create a new empty BigSumTree element.
 *
 * # Arguments
 *
 * * `flags` - Optional element flags (may be null/empty)
 *
 * # Returns
 *
 * A new element. Caller must free with `grovedb_free_element()`.
 */
struct GroveDbElement *grovedb_element_new_big_sum_tree(struct ByteBuffer flags);

/**
 * Create a new empty CountTree element.
 *
 * # Arguments
 *
 * * `flags` - Optional element flags (may be null/empty)
 *
 * # Returns
 *
 * A new element. Caller must free with `grovedb_free_element()`.
 */
struct GroveDbElement *grovedb_element_new_count_tree(struct ByteBuffer flags);

/**
 * Create a new empty CountSumTree element.
 *
 * # Arguments
 *
 * * `flags` - Optional element flags (may be null/empty)
 *
 * # Returns
 *
 * A new element. Caller must free with `grovedb_free_element()`.
 */
struct GroveDbElement *grovedb_element_new_count_sum_tree(struct ByteBuffer flags);

/**
 * Create a new Reference element with an absolute path.
 *
 * # Arguments
 *
 * * `path` - The absolute path to reference
 * * `max_hops` - Maximum reference hops (0 for no limit)
 * * `flags` - Optional element flags (may be null/empty)
 * * `error_out` - Pointer to receive error details (may be null)
 *
 * # Returns
 *
 * A new element, or null on error. Caller must free with `grovedb_free_element()`.
 *
 * # Safety
 *
 * * `path` must be valid during the call
 */
struct GroveDbElement *grovedb_element_new_reference(const struct GroveDbPath *path,
                                                     uint8_t max_hops,
                                                     struct ByteBuffer flags,
                                                     struct GroveDbError *error_out);

/**
 * Get the type of an element.
 *
 * # Arguments
 *
 * * `element` - The element to inspect
 *
 * # Returns
 *
 * The element type, or `Item` if the element is null.
 */
enum GroveDbElementType grovedb_element_get_type(const struct GroveDbElement *element);

/**
 * Free an element allocated by grovedb-ffi.
 *
 * # Safety
 *
 * * `element` must have been allocated by grovedb-ffi
 * * `element` must not be used after this call
 * * It is safe to pass null (no-op)
 */
void grovedb_free_element(struct GroveDbElement *element);

/**
 * Free a null-terminated string allocated by grovedb-ffi.
 *
 * # Safety
 *
 * * `s` must have been allocated by grovedb-ffi (e.g., from error messages)
 * * `s` must not be used after this call
 * * It is safe to pass null (no-op)
 */
void grovedb_free_string(char *s);

/**
 * Free an owned byte buffer allocated by grovedb-ffi.
 *
 * # Safety
 *
 * * `buf` must point to a valid OwnedByteBuffer or be null
 * * The buffer must have been allocated by grovedb-ffi
 * * The buffer must not be used after this call
 * * It is safe to pass null (no-op)
 */
void grovedb_free_byte_buffer(struct OwnedByteBuffer *buf);

/**
 * Free an owned path allocated by grovedb-ffi.
 *
 * This frees all segments and the segment array.
 *
 * # Safety
 *
 * * `path` must point to a valid GroveDbPathOwned or be null
 * * The path must have been allocated by grovedb-ffi
 * * The path must not be used after this call
 * * It is safe to pass null (no-op)
 */
void grovedb_free_path_owned(struct GroveDbPathOwned *path);

/**
 * Free an error structure allocated by grovedb-ffi.
 *
 * This frees the error message string if present.
 *
 * # Safety
 *
 * * `error` must point to a valid GroveDbError or be null
 * * The error must not be used after this call
 * * It is safe to pass null (no-op)
 */
void grovedb_free_error(struct GroveDbError *error);

/**
 * Generate a proof for a query.
 *
 * # Arguments
 *
 * * `handle` - Database handle
 * * `query` - PathQuery handle (consumed - do not use after this call)
 * * `error_out` - Pointer to receive error details (may be null)
 *
 * # Returns
 *
 * The serialized proof as a byte buffer, or null buffer on error.
 * Caller must free with `grovedb_free_byte_buffer()`.
 *
 * # Safety
 *
 * * `handle` must be a valid database handle
 * * `query` is consumed by this call
 */
struct OwnedByteBuffer grovedb_prove_query(const struct grovedb_t *handle,
                                           struct grovedb_path_query_t *query,
                                           struct GroveDbError *error_out);

/**
 * Generate a proof for a single-key query.
 *
 * This is a convenience function that combines query creation and proof generation.
 *
 * # Arguments
 *
 * * `handle` - Database handle
 * * `path` - The path to query
 * * `key` - The key to prove
 * * `error_out` - Pointer to receive error details (may be null)
 *
 * # Returns
 *
 * The serialized proof as a byte buffer, or null buffer on error.
 * Caller must free with `grovedb_free_byte_buffer()`.
 *
 * # Safety
 *
 * * `handle` must be a valid database handle
 * * `path` and `key` data must be valid during the call
 */
struct OwnedByteBuffer grovedb_prove_query_key(const struct grovedb_t *handle,
                                               const struct GroveDbPath *path,
                                               struct ByteBuffer key,
                                               struct GroveDbError *error_out);

/**
 * Verify a proof against a query.
 *
 * This is a static method that does not require a database handle.
 * It verifies that the proof is valid for the given query and returns
 * the root hash and query results.
 *
 * # Arguments
 *
 * * `proof` - The serialized proof bytes
 * * `path` - The path that was queried
 * * `key` - The key that was queried (for single-key verification)
 * * `root_hash_out` - Pointer to 32-byte buffer to receive the verified root hash
 * * `error_out` - Pointer to receive error details (may be null)
 *
 * # Returns
 *
 * Query results if verification succeeds, or null on error.
 * Caller must free with `grovedb_free_query_results()`.
 *
 * # Safety
 *
 * * `proof` data must be valid during the call
 * * `root_hash_out` must point to at least 32 bytes of writable memory
 */
struct QueryResults *grovedb_verify_query_key(struct ByteBuffer proof,
                                              const struct GroveDbPath *path,
                                              struct ByteBuffer key,
                                              uint8_t (*root_hash_out)[32],
                                              struct GroveDbError *error_out);

/**
 * Verify a proof against a custom query.
 *
 * This verifies a proof using a PathQuery builder that was configured
 * with the same parameters as the original proof generation.
 *
 * # Arguments
 *
 * * `proof` - The serialized proof bytes
 * * `query` - PathQuery handle (consumed - do not use after this call)
 * * `root_hash_out` - Pointer to 32-byte buffer to receive the verified root hash
 * * `error_out` - Pointer to receive error details (may be null)
 *
 * # Returns
 *
 * Query results if verification succeeds, or null on error.
 * Caller must free with `grovedb_free_query_results()`.
 *
 * # Safety
 *
 * * `proof` data must be valid during the call
 * * `query` is consumed by this call
 * * `root_hash_out` must point to at least 32 bytes of writable memory
 */
struct QueryResults *grovedb_verify_query(struct ByteBuffer proof,
                                          struct grovedb_path_query_t *query,
                                          uint8_t (*root_hash_out)[32],
                                          struct GroveDbError *error_out);

/**
 * Verify a proof with absence proof support.
 *
 * This verifies a proof that may include proofs of absence for non-existing keys.
 *
 * # Arguments
 *
 * * `proof` - The serialized proof bytes
 * * `query` - PathQuery handle (consumed - do not use after this call)
 * * `root_hash_out` - Pointer to 32-byte buffer to receive the verified root hash
 * * `error_out` - Pointer to receive error details (may be null)
 *
 * # Returns
 *
 * Query results if verification succeeds, or null on error.
 * Caller must free with `grovedb_free_query_results()`.
 *
 * # Safety
 *
 * * `proof` data must be valid during the call
 * * `query` is consumed by this call
 * * `root_hash_out` must point to at least 32 bytes of writable memory
 */
struct QueryResults *grovedb_verify_query_with_absence_proof(struct ByteBuffer proof,
                                                             struct grovedb_path_query_t *query,
                                                             uint8_t (*root_hash_out)[32],
                                                             struct GroveDbError *error_out);

/**
 * Create a new PathQuery builder for the given path.
 *
 * # Arguments
 *
 * * `path` - The path to query (may be null for root)
 * * `error_out` - Pointer to receive error details (may be null)
 *
 * # Returns
 *
 * A PathQuery handle, or null on error.
 * Use `grovedb_path_query_*` functions to configure, then execute or free.
 *
 * # Safety
 *
 * * `path` segments must remain valid during the call
 */
struct grovedb_path_query_t *grovedb_path_query_new(const struct GroveDbPath *path,
                                                    struct GroveDbError *error_out);

/**
 * Add a single key to the query.
 *
 * # Arguments
 *
 * * `query` - PathQuery handle
 * * `key` - The key to query
 * * `error_out` - Pointer to receive error details (may be null)
 *
 * # Returns
 *
 * `true` on success, `false` on error.
 *
 * # Safety
 *
 * * `query` must be a valid PathQuery handle
 * * `key` data must be valid during the call
 */
bool grovedb_path_query_add_key(struct grovedb_path_query_t *query,
                                struct ByteBuffer key,
                                struct GroveDbError *error_out);

/**
 * Add a range query [start, end).
 *
 * # Arguments
 *
 * * `query` - PathQuery handle
 * * `start` - Range start (inclusive)
 * * `end` - Range end (exclusive)
 * * `error_out` - Pointer to receive error details (may be null)
 *
 * # Returns
 *
 * `true` on success, `false` on error.
 */
bool grovedb_path_query_add_range(struct grovedb_path_query_t *query,
                                  struct ByteBuffer start,
                                  struct ByteBuffer end,
                                  struct GroveDbError *error_out);

/**
 * Add a range query [start, end].
 *
 * # Arguments
 *
 * * `query` - PathQuery handle
 * * `start` - Range start (inclusive)
 * * `end` - Range end (inclusive)
 * * `error_out` - Pointer to receive error details (may be null)
 *
 * # Returns
 *
 * `true` on success, `false` on error.
 */
bool grovedb_path_query_add_range_inclusive(struct grovedb_path_query_t *query,
                                            struct ByteBuffer start,
                                            struct ByteBuffer end,
                                            struct GroveDbError *error_out);

/**
 * Add a full range query (all keys).
 *
 * # Arguments
 *
 * * `query` - PathQuery handle
 * * `error_out` - Pointer to receive error details (may be null)
 *
 * # Returns
 *
 * `true` on success, `false` on error.
 */
bool grovedb_path_query_add_range_full(struct grovedb_path_query_t *query,
                                       struct GroveDbError *error_out);

/**
 * Add a range from query [start, ..].
 *
 * # Arguments
 *
 * * `query` - PathQuery handle
 * * `start` - Range start (inclusive)
 * * `error_out` - Pointer to receive error details (may be null)
 *
 * # Returns
 *
 * `true` on success, `false` on error.
 */
bool grovedb_path_query_add_range_from(struct grovedb_path_query_t *query,
                                       struct ByteBuffer start,
                                       struct GroveDbError *error_out);

/**
 * Add a range after query (start, ..].
 *
 * # Arguments
 *
 * * `query` - PathQuery handle
 * * `start` - Range start (exclusive)
 * * `error_out` - Pointer to receive error details (may be null)
 *
 * # Returns
 *
 * `true` on success, `false` on error.
 */
bool grovedb_path_query_add_range_after(struct grovedb_path_query_t *query,
                                        struct ByteBuffer start,
                                        struct GroveDbError *error_out);

/**
 * Set the result limit for the query.
 *
 * # Arguments
 *
 * * `query` - PathQuery handle
 * * `limit` - Maximum number of results to return
 */
void grovedb_path_query_set_limit(struct grovedb_path_query_t *query, uint16_t limit);

/**
 * Set the result offset for the query.
 *
 * # Arguments
 *
 * * `query` - PathQuery handle
 * * `offset` - Number of results to skip
 */
void grovedb_path_query_set_offset(struct grovedb_path_query_t *query, uint16_t offset);

/**
 * Execute a query on the database.
 *
 * # Arguments
 *
 * * `handle` - Database handle
 * * `query` - PathQuery handle (consumed - do not use after this call)
 * * `transaction` - Optional transaction handle (may be null)
 * * `error_out` - Pointer to receive error details (may be null)
 *
 * # Returns
 *
 * Query results, or null on error. Caller must free with `grovedb_free_query_results()`.
 *
 * # Safety
 *
 * * `handle` must be a valid database handle
 * * `query` is consumed by this call
 */
struct QueryResults *grovedb_query(const struct grovedb_t *handle,
                                   struct grovedb_path_query_t *query,
                                   const struct grovedb_transaction_t *transaction,
                                   struct GroveDbError *error_out);

/**
 * Create a simple single-key query and execute it.
 *
 * This is a convenience function that combines path_query_new, add_key, and query.
 *
 * # Arguments
 *
 * * `handle` - Database handle
 * * `path` - The path to query
 * * `key` - The key to query
 * * `transaction` - Optional transaction handle (may be null)
 * * `error_out` - Pointer to receive error details (may be null)
 *
 * # Returns
 *
 * Query results, or null on error. Caller must free with `grovedb_free_query_results()`.
 */
struct QueryResults *grovedb_query_key(const struct grovedb_t *handle,
                                       const struct GroveDbPath *path,
                                       struct ByteBuffer key,
                                       const struct grovedb_transaction_t *transaction,
                                       struct GroveDbError *error_out);

/**
 * Free a PathQuery handle without executing it.
 *
 * # Arguments
 *
 * * `query` - PathQuery handle to free (may be null)
 *
 * # Safety
 *
 * * `query` must have been returned by `grovedb_path_query_new()`
 * * `query` must not be used after this call
 */
void grovedb_free_path_query(struct grovedb_path_query_t *query);

/**
 * Free query results.
 *
 * # Arguments
 *
 * * `results` - Query results to free (may be null)
 *
 * # Safety
 *
 * * `results` must have been returned by a query function
 * * `results` must not be used after this call
 */
void grovedb_free_query_results(struct QueryResults *results);

/**
 * Get the number of results in a query result set.
 *
 * # Arguments
 *
 * * `results` - Query results
 *
 * # Returns
 *
 * Number of results, or 0 if results is null.
 */
size_t grovedb_query_results_count(const struct QueryResults *results);

/**
 * Get a result element at the specified index.
 *
 * # Arguments
 *
 * * `results` - Query results
 * * `index` - Index of the result to get
 *
 * # Returns
 *
 * Pointer to the result element, or null if out of bounds.
 * The returned pointer is valid until the results are freed.
 *
 * # Safety
 *
 * * `results` must be valid
 */
const struct QueryResultElement *grovedb_query_results_get(const struct QueryResults *results,
                                                           size_t index);

/**
 * Start a new transaction.
 *
 * All operations using this transaction will be isolated until commit or rollback.
 *
 * # Arguments
 *
 * * `handle` - Database handle
 * * `error_out` - Pointer to receive error details (may be null)
 *
 * # Returns
 *
 * A transaction handle, or null on error.
 * Use `grovedb_commit_transaction()` or `grovedb_rollback_transaction()` to finish.
 * The handle is automatically freed when committed.
 * For rollback, you can continue using the transaction or free it with
 * `grovedb_free_transaction()`.
 *
 * # Safety
 *
 * * `handle` must be a valid database handle
 */
struct grovedb_transaction_t *grovedb_start_transaction(const struct grovedb_t *handle,
                                                        struct GroveDbError *error_out);

/**
 * Commit a transaction.
 *
 * All changes made within the transaction are persisted to the database.
 * The transaction handle is consumed and should not be used after this call.
 *
 * # Arguments
 *
 * * `handle` - Database handle
 * * `transaction` - Transaction handle to commit (consumed on success)
 * * `error_out` - Pointer to receive error details (may be null)
 *
 * # Returns
 *
 * `true` on success, `false` on error.
 *
 * # Safety
 *
 * * `handle` must be a valid database handle
 * * `transaction` must be a valid transaction handle from this database
 * * `transaction` must not be used after successful commit
 */
bool grovedb_commit_transaction(const struct grovedb_t *handle,
                                struct grovedb_transaction_t *transaction,
                                struct GroveDbError *error_out);

/**
 * Rollback a transaction.
 *
 * All changes made within the transaction are discarded.
 * After rollback, the transaction is invalidated and cannot be reused.
 * Free the transaction handle with `grovedb_free_transaction()`.
 *
 * # Arguments
 *
 * * `handle` - Database handle
 * * `transaction` - Transaction handle to rollback
 * * `error_out` - Pointer to receive error details (may be null)
 *
 * # Returns
 *
 * `true` on success, `false` on error.
 *
 * # Safety
 *
 * * `handle` must be a valid database handle
 * * `transaction` must be a valid transaction handle from this database
 * * `transaction` cannot be used for operations after rollback
 */
bool grovedb_rollback_transaction(const struct grovedb_t *handle,
                                  const struct grovedb_transaction_t *transaction,
                                  struct GroveDbError *error_out);

/**
 * Abort a transaction without commit or rollback.
 *
 * This simply drops the transaction, discarding any uncommitted changes.
 * Use this when you want to cancel a transaction without going through
 * the normal rollback process.
 *
 * # Arguments
 *
 * * `handle` - Database handle
 * * `transaction` - Transaction handle to abort (consumed)
 *
 * # Returns
 *
 * `true` if the transaction was found and aborted, `false` if not found.
 *
 * # Safety
 *
 * * `handle` must be a valid database handle
 * * `transaction` must not be used after this call
 */
bool grovedb_abort_transaction(const struct grovedb_t *handle,
                               struct grovedb_transaction_t *transaction);

/**
 * Free a transaction handle.
 *
 * Use this to free a transaction handle that was rolled back and is no longer needed,
 * or to clean up after an error. Do not use on committed transactions (they are
 * automatically freed).
 *
 * # Arguments
 *
 * * `transaction` - Transaction handle to free (may be null)
 *
 * # Safety
 *
 * * `transaction` must have been returned by `grovedb_start_transaction()`
 * * `transaction` must not be used after this call
 */
void grovedb_free_transaction(struct grovedb_transaction_t *transaction);

/**
 * Check if a transaction is active.
 *
 * # Arguments
 *
 * * `handle` - Database handle
 * * `transaction` - Transaction handle to check
 *
 * # Returns
 *
 * `true` if the transaction is active, `false` otherwise.
 *
 * # Safety
 *
 * * `handle` must be a valid database handle
 * * `transaction` must be a valid transaction handle
 */
bool grovedb_is_transaction_active(const struct grovedb_t *handle,
                                   const struct grovedb_transaction_t *transaction);

#ifdef __cplusplus
} // extern "C"
#endif // __cplusplus

#endif /* GROVEDB_FFI_H */
