name: Prevent Merging into Master

on:
  pull_request:
    branches:
      - develop
jobs:
  ClangFormat:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run Clang-Format-Diff.py
        run: git diff -U0 develop.. | ./contrib/devtools/clang-format-diff.py -p1

