name: conflibot
on: pull_request

permissions:
  contents: read
  pull-requests: write
  # Enforce other not needed permissions are off
  actions: none
  checks: none
  deployments: none
  issues: none
  packages: none
  repository-projects: none
  security-events: none
  statuses: none


jobs:
  conflibot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Warn potential conflicts
        uses: wktk/conflibot@v1.1.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          exclude: |
            yarn.lock
            **/*.bin
