on: [push, pull_request]

jobs:
  guix_build:
    runs-on: ubuntu-latest
    container:
      image: alpine-guix
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          repository: dashpay/dash

      - name: Run Guix build
        run: contrib/guix/guix-build
