name: Guix Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git make bash curl bzip2 ca-certificates guix
          sudo locale-gen en_US.UTF-8
        shell: bash

      - name: Run Guix Build
        run: |
          ls /
          ls
          cd dash/contrib/guix
          ./guix-build
        shell: bash
