name: Guix Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git make bash curl bzip2 ca-certificates shadow
          sudo locale-gen en_US.UTF-8
          sudo update-ca-certificates
        shell: bash

      - name: Install Guix
        run: |
          sudo mkdir -p /usr/local/guix
          sudo chown -R $(whoami) /usr/local/guix
          curl -L https://git.io/JYOYR | tar xzf - --strip-components=1 -C /usr/local/guix
          echo 'export GUIX_LOCPATH=$HOME/.guix-profile/lib/locale' >> ~/.bashrc
          echo 'export PATH="$HOME/.guix-profile/bin:$PATH"' >> ~/.bashrc
          . $HOME/.bashrc
          guix pull
        shell: bash

      - name: Run Guix Build
        run: |
          cd dash/contrib/guix
          ./guix-build
        shell: bash
