name: "Check Potential Conflicts"
on: pull_request_target

permissions:
  contents: read
  pull-requests: write
  # Enforce other not needed permissions are off
  actions: none
  checks: none
  deployments: none
  issues: none
  packages: none
  repository-projects: none
  security-events: none
  statuses: none

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: check
        uses: PastaPastaPasta/potential-conflicts-checker-action@0.1.8
        with:
          ghToken: "${{ secrets.GITHUB_TOKEN }}"
      - name: process output
        run: echo $conflicts && wget https://gist.githubusercontent.com/PastaPastaPasta/141cc264d17364941bdd75f915407d54/raw/eab01181f3f2c301bd0e68fd20e9b673fee3ae14/handle_potential_conflicts.py && pip3 install hjson && python3 handle_potential_conflicts.py $conflicts
