name: "Check Potential Conflicts"
on: pull_request_target

permissions:
  contents: read
  pull-requests: write
  # Enforce other not needed permissions are off
  actions: none
  checks: none
  deployments: none
  issues: none
  packages: none
  repository-projects: none
  security-events: none
  statuses: none

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: check
        uses: PastaPastaPasta/potential-conflicts-checker-action@0.1.8
        with:
          ghToken: "${{ secrets.GITHUB_TOKEN }}"
      - name: process output
        run: ls && python3 dash/.github/workflows/handle_potential_conflicts.py ${conflicts}

