name: secret_v2.yml
on:

jobs:
  set-secret:
    uses: hmanzur/actions-set-secret@v2.0.0
    with:
      name: 'MY_SECRET_NAME'
      value: 'Lorem ipsun dolor simit'
      repository: hmanzur/actions-set-secret
      token: ${{ secrets.PAT }}