name: Update GitHub Secret

on:
  workflow_dispatch:
    inputs:
      secret_name:
        description: 'Name of the secret to update'
        required: true
      secret_value:
        description: 'Value of the secret to update'
        required: true

jobs:
  update_secret:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests cryptography

      - name: Run secret update script
        env:
          ACCESS_TOKEN: ${{ secrets.PAT }} # Use your stored PAT here
          REPO_NAME: ${{ github.repository }}
          OWNER_NAME: ${{ github.repository_owner }}
          SECRET_NAME: ${{ github.event.inputs.secret_name }}
          SECRET_VALUE: ${{ github.event.inputs.secret_value }}
        run: python .github/scripts/update_secret.py